# Generated by Django 3.1.7 on 2021-03-05 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('RevisionDate', models.DateField(default=datetime.datetime(2021, 3, 7, 12, 19, 42, 437470, tzinfo=utc))),
                ('TotalRevision', models.IntegerField(default=0)),
                ('topic', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
