# Generated by Django 3.1.7 on 2021-03-07 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='RevisionDate',
            field=models.DateField(default=datetime.datetime(2021, 3, 9, 13, 44, 48, 745406, tzinfo=utc)),
        ),
    ]
