# Generated by Django 3.1.7 on 2021-03-07 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20210307_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='RevisionDate',
            field=models.DateField(default=datetime.datetime(2021, 3, 9, 13, 48, 36, 784855, tzinfo=utc)),
        ),
    ]
